package com.rs.game.content.skills.magic.lunar

import com.rs.game.content.skills.magic.Rune
import com.rs.game.content.skills.magic.RuneSet

enum class LunarSpell(val level: Int, val displayName: String, val xp: Double?, val runes: RuneSet?) {
    LUNAR_HOME(0, "Lunar Home Teleport", null, null),
    BAKE_PIE(65, "Bake Pie", 60.0, RuneSet(Rune.ASTRAL, 1, Rune.FIRE, 5, Rune.WATER, 4)),
    CURE_PLANT(66, "Cure Plant", 60.0, RuneSet(Rune.ASTRAL, 1, Rune.EARTH, 8)),
    MONSTER_EXAMINE(66, "Monster Examine", 61.0, RuneSet(Rune.ASTRAL, 1, Rune.COSMIC, 1, Rune.MIND, 1)),
    NPC_CONTACT(67, "NPC Contact", 63.0, RuneSet(Rune.ASTRAL, 1, Rune.COSMIC, 1, Rune.AIR, 2)),
    CURE_OTHER(68, "Cure Other", 65.0, RuneSet(Rune.ASTRAL, 1, Rune.EARTH, 10, Rune.LAW, 1)),
    HUMIDIFY(68, "Humidify", 65.0, RuneSet(Rune.ASTRAL, 1, Rune.FIRE, 1, Rune.WATER, 3)),
    MOONCLAN_TELEPORT(69, "Moonclan Teleport", 66.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 2, Rune.LAW, 1)),
    TELE_GROUP_MOONCLAN(70, "Tele Group Moonclan", 67.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 4, Rune.LAW, 1)),
    CURE_ME(71, "Cure Me", 69.0, RuneSet(Rune.ASTRAL, 2, Rune.COSMIC, 2)),
    OURANIA_TELEPORT(71, "Ourania Teleport", 69.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 6, Rune.LAW, 1)),
    HUNTER_KIT(71, "Hunter Kit", 70.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 2)),
    WATERBIRTH_TELEPORT(72, "Waterbirth Teleport", 71.0, RuneSet(Rune.ASTRAL, 2, Rune.WATER, 1, Rune.LAW, 1)),
    SOUTH_FALADOR_TELEPORT(72, "South Falador Teleport", 70.0, RuneSet(Rune.ASTRAL, 2, Rune.LAW, 1, Rune.AIR, 2)),
    TELE_GROUP_WATERBIRTH(73, "Tele Group Waterbirth", 72.0, RuneSet(Rune.ASTRAL, 2, Rune.WATER, 5, Rune.LAW, 1)),
    CURE_GROUP(74, "Cure Group", 74.0, RuneSet(Rune.ASTRAL, 2, Rune.COSMIC, 2)),
    REPAIR_RUNE_POUCH(75, "Repair Rune Pouch", 75.0, RuneSet(Rune.ASTRAL, 2, Rune.COSMIC, 1, Rune.LAW, 1)),
    BARBARIAN_TELEPORT(75, "Barbarian Teleport", 76.0, RuneSet(Rune.ASTRAL, 2, Rune.FIRE, 3, Rune.LAW, 2)),
    STAT_SPY(75, "Stat Spy", 76.0, RuneSet(Rune.ASTRAL, 2, Rune.COSMIC, 1, Rune.BODY, 5)),
    NORTH_ARDOUGNE_TELEPORT(76, "North Ardougne Teleport", 76.0, RuneSet(Rune.ASTRAL, 2, Rune.LAW, 1, Rune.WATER, 5)),
    TELE_GROUP_BARBARIAN(76, "Tele Group Barbarian", 77.0, RuneSet(Rune.ASTRAL, 2, Rune.FIRE, 6, Rune.LAW, 2)),
    SUPERGLASS_MAKE(77, "Superglass Make", 78.0, RuneSet(Rune.ASTRAL, 2, Rune.FIRE, 6, Rune.AIR, 10)),
    REMOTE_FARM(78, "Remote Farm", 79.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 2, Rune.NATURE, 3)),
    KHAZARD_TELEPORT(78, "Khazard Teleport", 80.0, RuneSet(Rune.ASTRAL, 2, Rune.WATER, 4, Rune.LAW, 2)),
    TELE_GROUP_KHAZARD(79, "Tele Group Khazard", 81.0, RuneSet(Rune.ASTRAL, 2, Rune.WATER, 8, Rune.LAW, 2)),
    DREAM(79, "Dream", 82.0, RuneSet(Rune.ASTRAL, 2, Rune.COSMIC, 1, Rune.BODY, 5)),
    SPIRITUALISE_FOOD(80, "Spiritualise Food", 81.0, RuneSet(Rune.ASTRAL, 2, Rune.COSMIC, 3, Rune.BODY, 5)),
    STRING_JEWELLERY(80, "String Jewellery", 87.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 10, Rune.WATER, 5)),
    STAT_RESTORE_POT_SHARE(81, "Stat Restore Pot Share", 84.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 10, Rune.WATER, 10)),
    MAGIC_IMBUE(82, "Magic Imbue", 86.0, RuneSet(Rune.ASTRAL, 2, Rune.FIRE, 7, Rune.WATER, 7)),
    MAKE_LEATHER(83, "Make Leather", 87.0, RuneSet(Rune.ASTRAL, 2, Rune.BODY, 2, Rune.FIRE, 2)),
    FERTILE_SOIL(83, "Fertile Soil", 87.0, RuneSet(Rune.ASTRAL, 3, Rune.EARTH, 15, Rune.NATURE, 2)),
    BOOST_POTION_SHARE(84, "Boost Potion Share", 88.0, RuneSet(Rune.ASTRAL, 3, Rune.EARTH, 12, Rune.WATER, 10)),
    FISHING_GUILD_TELEPORT(85, "Fishing Guild Teleport", 89.0, RuneSet(Rune.ASTRAL, 3, Rune.WATER, 10, Rune.LAW, 3)),
    TELE_GROUP_FISHING_GUILD(86, "Tele Group Fishing Guild", 90.0, RuneSet(Rune.ASTRAL, 3, Rune.WATER, 14, Rune.LAW, 3)),
    PLANK_MAKE(86, "Plank Make", 90.0, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 15, Rune.NATURE, 1)),
    CATHERBY_TELEPORT(87, "Catherby Teleport", 92.0, RuneSet(Rune.ASTRAL, 3, Rune.WATER, 10, Rune.LAW, 3)),
    TUNE_BANE_ORE(87, "Tune Bane Ore", null, RuneSet(Rune.ASTRAL, 2, Rune.EARTH, 4)),
    TELE_GROUP_CATHERBY(88, "Tele Group Catherby", 93.0, RuneSet(Rune.ASTRAL, 3, Rune.WATER, 12, Rune.LAW, 3)),
    ICE_PLATEAU_TELEPORT(89, "Ice Plateau Teleport", 96.0, RuneSet(Rune.ASTRAL, 3, Rune.WATER, 8, Rune.LAW, 3)),
    TELE_GROUP_ICE_PLATEAU(90, "Tele Group Ice Plateau", 99.0, RuneSet(Rune.ASTRAL, 3, Rune.WATER, 16, Rune.LAW, 3)),
    DISRUPTION_SHIELD(90, "Disruption Shield", 97.0, RuneSet(Rune.ASTRAL, 3, Rune.BLOOD, 3, Rune.BODY, 10)),
    ENERGY_TRANSFER(91, "Energy Transfer", 100.0, RuneSet(Rune.ASTRAL, 3, Rune.LAW, 2, Rune.NATURE, 1)),
    HEAL_OTHER(92, "Heal Other", 101.0, RuneSet(Rune.ASTRAL, 3, Rune.BLOOD, 1, Rune.LAW, 3)),
    TELEPORT_TO_TROLLHEIM(92, "Teleport to Trollheim", 101.0, RuneSet(Rune.ASTRAL, 3, Rune.LAW, 3, Rune.WATER, 10)),
    TELE_GROUP_TROLLHEIM(93, "Group Teleport to Trollheim", 102.0, RuneSet(Rune.ASTRAL, 3, Rune.LAW, 3, Rune.WATER, 20)),
    VENGEANCE_OTHER(93, "Vengeance Other", 108.0, RuneSet(Rune.ASTRAL, 3, Rune.EARTH, 10, Rune.DEATH, 2)),
    VENGEANCE(94, "Vengeance", 112.0, RuneSet(Rune.ASTRAL, 4, Rune.EARTH, 10, Rune.DEATH, 2)),
    VENGEANCE_GROUP(95, "Vengeance Group", 120.0, RuneSet(Rune.ASTRAL, 4, Rune.EARTH, 11, Rune.DEATH, 3)),
    HEAL_GROUP(95, "Heal Group", 124.0, RuneSet(Rune.ASTRAL, 4, Rune.BLOOD, 3, Rune.LAW, 6)),
    SPELLBOOK_SWAP(96, "Spellbook Swap", 130.0, RuneSet(Rune.ASTRAL, 3, Rune.COSMIC, 2, Rune.LAW, 1)),
    BORROWED_POWER(99, "Borrowed Power", null, RuneSet(Rune.ASTRAL, 3));

}